---
title: "VDH_Kimbe_AlphaDiversityPlot"
output: html_document
date: "2025-10-23"
---

#Packages
```{r}
library(tidyverse)
library(emmeans)
library(ggpubr)
library(ggplot2)
library(cowplot)
library(grid)
library(extrafont)
library(glmmTMB)

my_font <- "Arial"

```

#Manipulate Data Frame
```{r}
kimbe_combined_df_S$SampleType <- "Sediment"
kimbe_shannon_combined_df_S$SampleType <- "Sediment"

kimbe_combined_df_W$SampleType <- "Water"
kimbe_shannon_combined_df_W$SampleType <- "Water"

```


Plots 

#Sediment
## Chao1
```{r}
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_combined_df_S.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_poisson_S_Depth2.RData")

Kimbe.Sed.chao_v1 <-emmeans(kimbe_model_poisson_S_Depth2, ~Location|DepthCategory, regrid = "response") %>% 
  as_tibble() %>% 
  filter(! (Location == "KM" & DepthCategory == "Shallow")) %>% 
  filter(! (Location == "KE" & DepthCategory == "Shallow")) %>%
  #rename(low = asymp.LCL, 
         #hhl = hh ) %>% 
  #mutate(Index = "Chao1", 
         #Domain = "Sediment")

  ggplot() +
   geom_pointrange(aes(x = Location, y = response, ymin = asymp.LCL, ymax = asymp.UCL, shape = DepthCategory), 
                   position = position_dodge(width = .4), col = "coral2") +
   geom_point(data = kimbe_combined_df_S, aes(y = Chao1, x = Location, group = DepthCategory), 
              position = position_dodge(width = .4), col = "coral2", alpha = .2) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
   theme_classic() +
   labs(y = "Chao1", x = "") +
  guides(shape = guide_legend(title = "")) +
   theme(axis.line = element_blank(),
         text = element_text(family = my_font,size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
         panel.border = element_rect(fill = "transparent"), 
         legend.position = "none") 

```

##Shannon
```{r}
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_shannon_gaussian4.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_shannon_combined_df_S.RData")

Kimbe.Sed.shannon_v1 <-emmeans(kimbe_model_shannon_gaussian4, ~Location|DepthCategory, regrid = "response") %>% 
  as_tibble()  %>% filter(! (Location == "KM" & DepthCategory == "Shallow")) %>%
  filter(! (Location == "KE" & DepthCategory == "Shallow")) %>%
  ggplot() +
   geom_pointrange(aes(x = Location, y = emmean, ymin = lower.CL, ymax = upper.CL, shape = DepthCategory), 
                   position = position_dodge(width = .4), col = "coral2") +
   geom_point(data = kimbe_shannon_combined_df_S, aes(y = Shannon, x = Location, group = DepthCategory)
              , position = position_dodge(width = .4), col = "coral2", alpha = .2) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
   theme_classic() +
   labs(y = "Shannon", x = "") + 
  guides(shape = guide_legend(title = "")) +
   theme(axis.line = element_blank(),
         text = element_text(family = my_font,size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
         panel.border = element_rect(fill = "transparent"), 
         legend.position = "none", legend.title = element_blank()) 
```


#Water
##Chao1
```{r}
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_combined_df_W.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_poisson_W_Depth2.RData")
Kimbe.Water.chao_v1 <-emmeans(kimbe_model_poisson_W_Depth2, ~Location|DepthCategory, regrid = "response") %>% 
  as_tibble()  %>% 
  ggplot() +
   geom_pointrange(aes(x = Location, y = response, ymin = asymp.LCL, ymax = asymp.UCL, shape = DepthCategory), 
                   position = position_dodge(width = .4), col = "steelblue") +
   geom_point(data = kimbe_combined_df_W, aes(y = Chao1, x = Location, group = DepthCategory), 
              position = position_dodge(width = .4), , col = "steelblue", alpha = .2) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
   theme_classic() +
   labs(y = "Chao1", x = "") +
  guides(shape = guide_legend(title = "")) +
   theme(axis.line = element_blank(),
         text = element_text(family = my_font,size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
         panel.border = element_rect(fill = "transparent"), 
         legend.position = "none", legend.title = element_blank()) 
```

##Shannon
```{r}
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_shannon_combined_df_W.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_shannon_gaussian_water2.RData")

Kimbe.Water.shannon_v1 <-emmeans(kimbe_model_shannon_gaussian_water2, ~Location|DepthCategory, regrid = "response") %>% 
  as_tibble() %>%
  ggplot() +
   geom_pointrange(aes(x = Location, y = response, ymin = lower.CL, ymax = upper.CL, shape = DepthCategory), 
                   position = position_dodge(width = .4), col = "steelblue") +
   geom_point(data = kimbe_shannon_combined_df_W, aes(y = Shannon, x = Location, group = DepthCategory), 
              position = position_dodge(width = .4), col = "steelblue", alpha = .2) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
   theme_classic() +
   labs(y = "Shannon", x = "") +
  guides(shape = guide_legend(title = "")) +
   theme(axis.line = element_blank(), 
         text = element_text(family = my_font, size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
         panel.border = element_rect(fill = "transparent"), 
         legend.position = "none", legend.title = element_blank()) 
```


```{r}
# Dummy data frame to build a legend
legend_data <- data.frame(
  SampleType = c("Water", "Sediment"),
  Depth = c("Deep", "Shallow"),
  x = 1,
  y = 1
)


# Create dummy plot just for legend
legend_plot <- ggplot(legend_data, aes(x = x, y = y, color = SampleType, shape = Depth)) +
  geom_point(size = 3.5) +
  scale_color_manual(values = c("Sediment" = "coral2", "Water" = "steelblue")) +
  theme_void() +
  theme(legend.position = "right", legend.title = element_blank(),text = element_text(family = my_font, size = 8))

# Extract legend
legend <- cowplot::get_legend(legend_plot)
library(ggpubr)
# Combine ggplots and legend
AlphaDiversityKAUSTPlot <- cowplot::plot_grid(
  ggarrange(Kimbe.Water.chao_v1, Kimbe.Water.shannon_v1, Kimbe.Sed.chao_v1, Kimbe.Sed.shannon_v1,
            labels = c("a", "b", "c", "d")),
  legend,
  rel_widths = c(5, 1)
)

ggsave(plot = AlphaDiversityKAUSTPlot, "/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/figures/Narage/AlphaDiversityKAUSTPlot.png", width = 4*1.6, height = 4)


```

#2 Panel combined plot
```{r}
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_combined_df_S.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_poisson_S_Depth2.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_combined_df_S.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_shannon_gaussian4.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_combined_df_W.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_poisson_W_Depth2.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_shannon_combined_df_W.RData")
load("/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/scripts/Kimbe/kimbe_model_shannon_gaussian_water2.RData")

# Combine Chao1 summary data
kimbe_chao_emm_water <- emmeans(kimbe_model_poisson_W_Depth2, ~Location|DepthCategory, regrid = "response") %>%
  as_tibble() %>% mutate(SampleType = "Water")
kimbe_chao_emm_sed <- emmeans(kimbe_model_poisson_S_Depth2, ~Location|DepthCategory, regrid = "response") %>%
  as_tibble() %>% 
  filter(!(Location == "KM" & DepthCategory == "Shallow")) %>%
  filter(!(Location == "KE" & DepthCategory == "Shallow")) %>%
  mutate(SampleType = "Sediment")

kimbe_chao_emm_all <- bind_rows(kimbe_chao_emm_water, kimbe_chao_emm_sed)

# Combine raw Chao1 data
kimbe_combined_df_all <- bind_rows(kimbe_combined_df_W, kimbe_combined_df_S)

# Combine Shannon summary data
kimbe_shannon_emm_water <- emmeans(kimbe_model_shannon_gaussian_water2, ~Location|DepthCategory, regrid = "response") %>%
  as_tibble() %>% mutate(SampleType = "Water", response = response)
kimbe_shannon_emm_sed <- emmeans(kimbe_model_shannon_gaussian4, ~Location|DepthCategory, regrid = "response") %>%
  as_tibble() %>% 
  filter(!(Location == "KM" & DepthCategory == "Shallow")) %>%
  filter(!(Location == "KE" & DepthCategory == "Shallow")) %>%
  mutate(SampleType = "Sediment", response = emmean)

kimbe_shannon_emm_all <- bind_rows(kimbe_shannon_emm_water, kimbe_shannon_emm_sed)

# Combine raw Shannon data
kimbe_shannon_df_all <- bind_rows(kimbe_shannon_combined_df_W, kimbe_shannon_combined_df_S)

# Match your custom labels
x_labels <- c("Control", "Non-Vent", "Vent")
x_positions <- c(1, 2, 3)

strip_colors <- c("Control" = "#d4a6c8", 
                  "Non-Vent" = "#2c9c99", 
                  "Vent" = "#ffef88")

# Create data frame for background boxes
label_backgrounds <- data.frame(
  xmin = x_positions - 0.5,
  xmax = x_positions + 0.5,
  ymin = -Inf,
  ymax = Inf,
  fill = strip_colors[x_labels],
  label = x_labels
)

kimbe_Chao1_plot <- ggplot() +
  geom_pointrange(data = kimbe_chao_emm_all,
                  aes(x = Location, y = response, ymin = asymp.LCL, ymax = asymp.UCL,
                      shape = DepthCategory, color = SampleType, group = DepthCategory),
                  position = position_dodge(width = 0.4)) +
  geom_point(data = kimbe_combined_df_all,
             aes(x = Location, y = Chao1, group = DepthCategory, color = SampleType),
             position = position_dodge(width = 0.4), alpha = 0.2) +
  scale_color_manual(values = c("Sediment" = "coral2", "Water" = "steelblue")) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
  labs(y = "Chao1", x = "") +
  theme_classic() +
  guides(shape = guide_legend(title = "Depth"), color = guide_legend(title = "Sample Type")) +
  theme(
    axis.line = element_blank(),
    text = element_text(family = my_font, size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
    panel.border = element_rect(fill = NA),
    legend.position = "none"
  )+
  scale_fill_identity()

kimbe_Shannon_plot <- ggplot() +
  geom_pointrange(data = kimbe_shannon_emm_all,
                  aes(x = Location, y = response, ymin = lower.CL, ymax = upper.CL,
                      shape = DepthCategory, color = SampleType, group = DepthCategory),
                  position = position_dodge(width = 0.4)) +
  geom_point(data = kimbe_shannon_df_all,
             aes(x = Location, y = Shannon,  color = SampleType, group = DepthCategory),
             position = position_dodge(width = 0.4), alpha = 0.2) +
  scale_color_manual(values = c("Sediment" = "coral2", "Water" = "steelblue")) +
  scale_x_discrete(labels = c("KM" = "Control", "KA" = "Lagoon A", "KD" = "Lagoon D", "KE" = "Lagoon E")) +
  labs(y = "Shannon", x = "") +
  theme_classic() +
  guides(shape = guide_legend(title = "Depth"), color = guide_legend(title = "Sample Type")) +
  theme(
    axis.line = element_blank(),
    text = element_text(family = my_font, size = 8),
    axis.text = element_text(family = my_font, size = 5, face = "bold"),
    panel.border = element_rect(fill = NA),
    legend.position = "none",
    #legend.key.size = units(.2)
  ) +
  scale_fill_identity()

# Create dummy plot just for legend
legend_plot <- ggplot(legend_data, aes(x = x, y = y, color = SampleType, shape = Depth)) +
  geom_point(size = 3.5) +
  scale_color_manual(values = c("Sediment" = "coral2", "Water" = "steelblue")) +
  theme_void() +
  theme(legend.position = "right", legend.title = element_blank(),
        text = element_text(family = my_font, size = 8))

# Extract legend
legend <- cowplot::get_legend(legend_plot)

# Combine Chao1 and Shannon plots with legend
KimbeAlphaDiversityOverlay <- cowplot::plot_grid(
  ggarrange(kimbe_Chao1_plot, kimbe_Shannon_plot,  labels = c("a", "b")),
  legend,
  rel_widths = c(5, 1)
)

ggsave( "/Users/oo21097/Desktop/MRES_Kimbe_Bay/Microbial_Data/figures/Kimbe/KimbeAlphaDiversityOverlay.jpg", plot = KimbeAlphaDiversityOverlay, width = 5.5, height = 3  , dpi = 600)
```

